version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
   configuration: uav_collision_avoidance/docs/conf.py

formats:
   - pdf

python:
   install:
   - requirements: uav_collision_avoidance/docs/requirements.txt
   - method: pip
     path: .
